AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Style/Documentation:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case

Layout/LineLength:
  Max: 120
  AllowedPatterns: ['(\A|\s)#'] # ignore comments

Lint/AmbiguousBlockAssociation:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false